import { 
  Globe, Shield, TrendingUp, CreditCard, Zap, Home, Code,
  Briefcase, DollarSign, Wallet, BarChart3, PieChart, LineChart, TrendingDown, Building2,
  Cpu, Database, Server, Smartphone, Tablet, Laptop, Monitor, Wifi, Router,
  Lock, LockOpen, Key, Eye, EyeOff, AlertTriangle, AlertCircle, Fingerprint,
  ShoppingCart, ShoppingBag, Package, Tag, Percent, Gift, Heart, Star,
  Mail, MessageSquare, Phone, PhoneCall, Send, Rss, Volume2, Bell,
  ArrowRight, ArrowLeft, ChevronRight, ChevronLeft, Compass, Maximize, Minimize,
  Settings, PenTool as Tool, Wrench, Edit, Trash2, Download, Upload, Copy, Search,
  Filter, Layers, Grid, List, Menu, X, Plus, Minus, Check, CheckCircle,
  Circle, Square, Calendar, Clock, Music, Film, Image, Video, Play, Pause, Square as SquareIcon,
  Maximize2, Minimize2, Printer, Smartphone as Mobile, Tablet as TabletIcon, Watch,
  BookOpen, Book, Bookmark, Flag, MapPin, Map, Navigation, Compass as CompassIcon,
  LogOut, LogIn, User, Users, UserPlus, UserCheck, UserX, UserOctagon,
  Mail as Inbox, Archive, Trash, BarChart, LineChart as LineChartIcon, PieChart as PieChartIcon, AreaChart: BarChart3,
  Award, Trophy, Target, TrendingUp as TrendingUpIcon, TrendingDown as TrendingDownIcon,
  Activity, Zap as ZapIcon, Battery, Wifi as WifiIcon, WifiOff, Signal,
  GitBranch, GitCommit, Github, Terminal, Code as CodeIcon,
  Command, Smartphone as SmartphoneIcon, Watch as WatchIcon, Headphones, Mic,
  Wind, Cloud, CloudRain, CloudSnow, Sun, Moon, Star as StarIcon, Heart as HeartIcon,
  Smile, Frown, Meh, Eye as EyeIcon, EyeOff as EyeOffIcon, EyeClosed: EyeOff,
  Inbox as InboxIcon, MessageCircle, MessageDot, Send as SendIcon, Mail as MailIcon, MailOpen,
  Copy as CopyIcon, Clipboard, ClipboardList, Layers as LayersIcon, Layout, Sliders,
  Maximize as MaximizeIcon, Minimize as MinimizeIcon, Maximize2 as Maximize2Icon, Minimize2 as Minimize2Icon,
  RotateCw, RotateCcw, RefreshCw, RefreshCcw, Check as CheckIcon, X as XIcon,
  Plus as PlusIcon, Minus as MinusIcon, Edit as EditIcon, Trash as TrashIcon,
  Download as DownloadIcon, Upload as UploadIcon, Save, SaveAs: Save,
  ZoomIn: Plus, ZoomOut: Minus, Slash, Hash, Asterisk, Percent as PercentIcon,
  DollarSign as DollarSignIcon, Euro: DollarSignIcon, PoundSterling: DollarSignIcon, CreditCard as CreditCardIcon,
  Wallet as WalletIcon, ShoppingCart as ShoppingCartIcon, ShoppingBag as ShoppingBagIcon,
} from 'lucide-react';
import React from 'react';

export const ICON_TYPES = [
  'Globe', 'Shield', 'TrendingUp', 'CreditCard', 'Zap', 'Home', 'Code',
  'Briefcase', 'DollarSign', 'Wallet', 'BarChart3', 'PieChart', 'LineChart', 'TrendingDown', 'Building2',
  'Cpu', 'Database', 'Server', 'Smartphone', 'Tablet', 'Laptop', 'Monitor', 'Wifi', 'Router',
  'Lock', 'LockOpen', 'Key', 'Eye', 'EyeOff', 'AlertTriangle', 'AlertCircle', 'Fingerprint',
  'ShoppingCart', 'ShoppingBag', 'Package', 'Tag', 'Percent', 'Gift', 'Heart', 'Star',
  'Mail', 'MessageSquare', 'Phone', 'PhoneCall', 'Send', 'Rss', 'Volume2', 'Bell',
  'ArrowRight', 'ArrowLeft', 'ChevronRight', 'ChevronLeft', 'Compass', 'Maximize', 'Minimize',
  'Settings', 'Tool', 'Wrench', 'Edit', 'Trash2', 'Download', 'Upload', 'Copy', 'Search',
  'Filter', 'Layers', 'Grid', 'List', 'Menu', 'X', 'Plus', 'Minus', 'Check', 'CheckCircle',
  'Circle', 'Square', 'Calendar', 'Clock', 'Music', 'Film', 'Image', 'Video', 'Play', 'Pause',
  'Maximize2', 'Minimize2', 'Printer', 'Mobile', 'Watch', 'BookOpen', 'Book', 'Bookmark', 'Flag', 'MapPin',
  'Map', 'Navigation', 'LogOut', 'LogIn', 'User', 'Users', 'UserPlus', 'UserCheck', 'Inbox', 'Archive',
  'Award', 'Trophy', 'Target', 'Activity', 'Battery', 'Signal', 'GitBranch', 'GitCommit', 'Github',
  'Terminal', 'Command', 'Headphones', 'Mic', 'Wind', 'Cloud', 'CloudRain', 'CloudSnow', 'Sun', 'Moon',
  'Smile', 'Frown', 'Meh', 'Clipboard', 'ClipboardList', 'Layout', 'Sliders', 'RotateCw', 'RotateCcw',
  'RefreshCw', 'RefreshCcw', 'Save', 'Hash', 'Asterisk', 'Euro', 'PoundSterling',
];

export const iconMap: Record<string, React.ComponentType<{ className: string }>> = {
  Globe, Shield, TrendingUp, CreditCard, Zap, Home, Code,
  Briefcase, DollarSign, Wallet, BarChart3, PieChart, LineChart, TrendingDown, Building2,
  Cpu, Database, Server, Smartphone, Tablet, Laptop, Monitor, Wifi, Router,
  Lock, LockOpen, Key, Eye, EyeOff, AlertTriangle, AlertCircle, Fingerprint,
  ShoppingCart, ShoppingBag, Package, Tag, Percent, Gift, Heart, Star,
  Mail, MessageSquare, Phone, PhoneCall, Send, Rss, Volume2, Bell,
  ArrowRight, ArrowLeft, ChevronRight, ChevronLeft, Compass, Maximize, Minimize,
  Settings, Tool, Wrench, Edit, Trash2, Download, Upload, Copy, Search,
  Filter, Layers, Grid, List, Menu, X, Plus, Minus, Check, CheckCircle,
  Circle, Square, Calendar, Clock, 'Music': Music, 'Film': Film, 'Image': Image, 'Video': Video, 'Play': Play, 'Pause': Pause,
  Maximize2, Minimize2, 'Printer': Printer, 'Mobile': Smartphone, 'Watch': Watch, 'BookOpen': BookOpen, 'Book': Book, 'Bookmark': Bookmark, 'Flag': Flag, 'MapPin': MapPin,
  Map, Navigation, 'LogOut': LogOut, 'LogIn': LogIn, 'User': User, 'Users': Users, 'UserPlus': UserPlus, 'UserCheck': UserCheck, 'Inbox': Mail, 'Archive': Archive,
  Award, Trophy, Target, 'Activity': Activity, 'Battery': Battery, 'Signal': Signal, 'GitBranch': GitBranch, 'GitCommit': GitCommit, 'Github': Github,
  Terminal, 'Command': Command, 'Headphones': Headphones, 'Mic': Mic, 'Wind': Wind, 'Cloud': Cloud, 'CloudRain': CloudRain, 'CloudSnow': CloudSnow, 'Sun': Sun, 'Moon': Moon,
  'Smile': Smile, 'Frown': Frown, 'Meh': Meh, 'Clipboard': Clipboard, 'ClipboardList': ClipboardList, 'Layout': Layout, 'Sliders': Sliders, 'RotateCw': RotateCw, 'RotateCcw': RotateCcw,
  'RefreshCw': RefreshCw, 'RefreshCcw': RefreshCcw, 'Save': Save, 'Hash': Hash, 'Asterisk': Asterisk, 'Euro': DollarSignIcon, 'PoundSterling': DollarSignIcon,
};

export function getIconTypes() {
  return ICON_TYPES;
}
